atomic:
  target: dev
  outputs:
    dev:
      type: firebolt
      client_id: <some client_id>
      client_secret: <some secret>
      database: demo_atomic_adtech
      schema: public
      threads: 10
      host: api.go.firebolt.io
      account_name: workshop-dev
      engine_name: demo_atomic_adtech_general_purpose