atomic:
  outputs:
    fb_app:
      type: firebolt
      client_id: "{{ env_var('FIREBOLT_CLIENT_ID') }}"
      client_secret: "{{ env_var('FIREBOLT_CLIENT_SECRET') }}"
      account_name: demo
      database: temp
      engine_name: elt_engine
      schema: test
      threads: 1
  target: fb_app
